#!/usr/bin/env python3

"""Save a latched OccupancyGrid as a Nav2-compatible PGM/YAML map pair."""

import math
from pathlib import Path

import rclpy
from rclpy.node import Node
from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy
from nav_msgs.msg import OccupancyGrid


class OccupancyGridSaver(Node):
    def __init__(self):
        super().__init__('occupancy_grid_saver')

        self.declare_parameter('map_topic', '/map')
        self.declare_parameter('map_file', 'map')

        self._map_file = Path(self.get_parameter('map_file').value).expanduser()
        self._saved = False
        self._shutdown_timer = None

        qos = QoSProfile(
            depth=1,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
        )
        self.create_subscription(
            OccupancyGrid,
            self.get_parameter('map_topic').value,
            self._save_map,
            qos,
        )
        self.get_logger().info(
            f'Waiting for map on {self.get_parameter("map_topic").value}...')

    def _save_map(self, occupancy_grid):
        if self._saved:
            return

        self._saved = True
        try:
            base_path = self._map_file.with_suffix('')
            base_path.parent.mkdir(parents=True, exist_ok=True)
            pgm_path = base_path.with_suffix('.pgm')
            yaml_path = base_path.with_suffix('.yaml')

            self._write_pgm(pgm_path, occupancy_grid)
            self._write_yaml(yaml_path, pgm_path, occupancy_grid)
            self.get_logger().info(
                f'Map saved: {pgm_path} and {yaml_path}')
        except Exception as error:
            self.get_logger().error(f'Failed to save map: {error}')
        finally:
            self._shutdown_timer = self.create_timer(0.1, self._shutdown)

    @staticmethod
    def _write_pgm(path, occupancy_grid):
        info = occupancy_grid.info
        width = info.width
        height = info.height
        data = occupancy_grid.data

        if len(data) != width * height:
            raise ValueError('OccupancyGrid data size does not match its dimensions')

        pixels = bytearray(width * height)
        for row in range(height):
            source_row = height - row - 1
            for column in range(width):
                occupancy = data[source_row * width + column]
                index = row * width + column
                if occupancy < 0:
                    pixels[index] = 205
                elif occupancy >= 100:
                    pixels[index] = 0
                elif occupancy == 0:
                    pixels[index] = 254
                else:
                    pixels[index] = round(254 - (occupancy * 254 / 100))

        with path.open('wb') as pgm_file:
            pgm_file.write(f'P5\n# Generated by carrierbot_slam\n{width} {height}\n255\n'.encode())
            pgm_file.write(pixels)

    @staticmethod
    def _write_yaml(path, pgm_path, occupancy_grid):
        origin = occupancy_grid.info.origin
        quaternion = origin.orientation
        yaw = math.atan2(
            2.0 * (quaternion.w * quaternion.z + quaternion.x * quaternion.y),
            1.0 - 2.0 * (quaternion.y * quaternion.y + quaternion.z * quaternion.z),
        )

        yaml_text = (
            f'image: {pgm_path.name}\n'
            f'mode: trinary\n'
            f'resolution: {occupancy_grid.info.resolution}\n'
            f'origin: [{origin.position.x}, {origin.position.y}, {yaw}]\n'
            'negate: 0\n'
            'occupied_thresh: 0.65\n'
            'free_thresh: 0.25\n'
        )
        path.write_text(yaml_text, encoding='utf-8')

    def _shutdown(self):
        self._shutdown_timer.cancel()
        rclpy.shutdown()


def main(args=None):
    rclpy.init(args=args)
    node = OccupancyGridSaver()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
